### PR TITLE
Monitoring for crAPI (Issue 118)

### PR DESCRIPTION
**Pull request by drraghavendra**
Monitoring for crAPI

## Description

#Issue118 https://github.com/OWASP/crAPI/issues/118
Provide an easy way to set up crAPI along with monitoring setup. For example, with Kubernetes setup, I should be able to monitor golden signals for my Kubernetes setup with Kube-state metrics.

Way to deploy an application with Prometheus and Grafana. The user should be able to create a Grafana dashboard out of the infra metrics from crAPI. We can also provide a dashboard template.

### CODE REVIEW

**Comment by drraghavendra** [comment]
@JBAhire Please look into this Code, make necessary changes as Iam not familiar with Environment changes.Kindly consider my request

**Comment by Apollo9999** [comment]
I think still lot of code needs to be added

**Comment by JBAhire** [comment]
Thanks, @drraghavendra . Will take a look and put comments if any.

**Comment by AHarmlessPyro** [comment]
@drraghavendra For this task, there are a few steps that have to be done
 - Add Grafana with the prometheus data ingestor. 
   - This is done for kubernetes and docker I think
 - Add an endpoint which publishes metrics that to use. This has to be done separately for all services (i.e., community, workshop, identity)
   - To be done. 

You can follow this example : https://thepylot.dev/setup-grafana-with-prometheus-for-python-projects-docker-included/

Some sample metrics we might want are : 
 - Requests per unit time (say second, minute, hour etc.)
 - Status code per unit time
 - Max request size in last unit time

**Comment by drraghavendra** [comment]
Please go through files [APP.zip](https://github.com/OWASP/crAPI/files/9740950/APP.zip)

**Comment by JBAhire** [comment]
@drraghavendra , can you please check in unzipped files in deployments directory?

**Review by Apollo9999 — COMMENTED** [review]
wrong comment

**Review by drraghavendra — COMMENTED** [review]
Checked in  for Deployments folder

**Comment by drraghavendra** [comment]
@JBAhire @piyushroshan code for Prometheus and Grafana working fine recheck again

**Pull request closed without merging**
