### PR TITLE
Improvements in user profile (Issue #128)

### PR DESCRIPTION
**Pull request by AHarmlessPyro**
## Description
Refer to Issue #128 
`Some users feel that the User Profile can be improved. It is not clear to everyone that you can click on the profile photo to update account info.`

Have added a `pointer` style cursor to profile. In addition, nested the profile avatar inside a container that highlights to a color (`#1890ff`, as used in other button style elements in UI). 

### Testing
Has been tested manually. 

### Documentation
N.A.

### Checklist:
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged
- [x] I have documented any changes if required in the [docs](docs).

### CODE REVIEW

**Comment by JBAhire** [comment]
Hey @AHarmlessPyro , can you please add screenshot for this in PR description?

**Comment by AHarmlessPyro** [comment]
Here you go @JBAhire  



Can't use a screenshot since cursor doesn't seem to be captured in mac os. This shows the highlight ring around the profile avatar along with the different cursor. 

I've tried to mimic the visual behavior of facebook a bit here since that works well while still keeping the clickable area limited to the avatar itself.

**Comment by JBAhire** [comment]
This looks good to me, @AHarmlessPyro ! Thanks for putting this together. @piyushroshan , please review.

**Review by JBAhire — APPROVED** [review]
LGTM.

**Review by piyushroshan — APPROVED** [review]

**Pull request merged**
