### PR TITLE
Adding crAPI architecture diagram and doc

### PR DESCRIPTION
**Pull request by testingGarage**
## Description
Please include a summary of the change, motivation and context.

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested the service locally. 

### Documentation
Make sure that you have documented corresponding changes in this repository. 

### Checklist:
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged
- [x] I have documented any changes if required in the [docs](docs).

### CODE REVIEW

**Comment by testingGarage** [comment]
@piyushroshan , @JBAhire 

I have made a document for crAPI Architecture.
Please review the PR.

**Review by piyushroshan — APPROVED** [review]
Perfect. Thank you for your contribution.
Good enough for first pass.

**Review by JBAhire — APPROVED** [review]
Thanks for the contribution, @testingGarage !

**Review by JBAhire — COMMENTED** [review]
Can you please rename the `pics` direcory to `images` directory?

**Comment by testingGarage** [comment]
> 
@JBAhire, 

I have renamed the directory name to 'images' from 'pics'.

**Review by piyushroshan — APPROVED** [review]

**Pull request merged**
