### PR TITLE
Added troubleshooting doc for general issues faced while installing and running crAPI

### PR DESCRIPTION
**Pull request by sanket-mundra**
Refers to this issue: [#117](https://github.com/OWASP/crAPI/issues/117)

## Description
Please include a summary of the change, motivation and context.

### Testing
Please describe the tests that you ran to verify your changes. Please summarize what did you test and what needs to be tested e.g. deployed and tested the service locally. 

### Documentation
Make sure that you have documented corresponding changes in this repository. 

### Checklist:
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] Any dependent changes have been merged
- [x] I have documented any changes if required in the [docs](docs).

### CODE REVIEW

**Comment by sanket-mundra** [comment]
Hey @JBAhire, I have created a google doc containing all the issues that I faced while installing and running crAPI. Please have a look.

**Comment by mathew-jose** [comment]
The guide covers the common issues we find. @piyushroshan @JBAhire would a markdown be more preferable than a google doc.

**Comment by piyushroshan** [comment]
Markdown would be more preferred as other can contribute to same yet can be controlled of malicious changes

**Comment by JBAhire** [comment]
Yup. @sanket-mundra , can you please create a `troubleshooting.md` in same docs directory and put content there.

**Comment by sanket-mundra** [comment]
Done @piyushroshan @JBAhire

**Comment by mathew-jose** [comment]
The doc looks good. I am getting a 404 error when I try to click `Troubleshooting guide crAPI` from the Readme.

**Comment by sanket-mundra** [comment]
Yeah @mathew-jose, the 404 is because the link is for the `troubleshooting.md` file is of the file in `OWASP/crAPI` repo but currently the file is in my forked repo. This error should go away once the PR is merged.

**Review by JBAhire — APPROVED** [review]
LGTM. Thanks @sanket-mundra !

**Pull request merged**
